// 假定的HTML字符串，包含多行
const htmlString = `
<tr>
    <td>Arabic</td>
    <td>阿拉伯语</td>
    <td>ar</td>
  </tr>
  <tr>
    <td>German</td>
    <td>德语</td>
    <td>de</td>
  </tr>
  <tr>
    <td>English</td>
    <td>英语</td>
    <td>en</td>
  </tr>
  <tr>
    <td>Spanish</td>
    <td>西班牙语</td>
    <td>es</td>
  </tr>
  <tr>
    <td>French</td>
    <td>法语</td>
    <td>fr</td>
  </tr>
  <tr>
    <td>Hindi</td>
    <td>印地语</td>
    <td colspan="2">hi</td>
  </tr>
  <tr>
    <td>Indonesian</td>
    <td>印度尼西亚语</td>
    <td>id</td>
  </tr>
  <tr>
    <td>Italian</td>
    <td>意大利语</td>
    <td>it</td>
  </tr>
  <tr>
    <td>Japanese</td>
    <td>日语</td>
    <td>ja</td>
  </tr>
  <tr>
    <td>Korean</td>
    <td>韩语</td>
    <td>ko</td>
  </tr>
  <tr>
    <td>Dutch</td>
    <td>荷兰语</td>
    <td>nl</td>
  </tr>
  <tr>
    <td>Portuguese</td>
    <td>葡萄牙语</td>
    <td>pt</td>
  </tr>
  <tr>
    <td>Russian</td>
    <td>俄语</td>
    <td>ru</td>
  </tr>
  <tr>
    <td>hai</td>
    <td>泰语</td>
    <td>th</td>
  </tr>
  <tr>
    <td>Vietnamese</td>
    <td>越南语</td>
    <td>vi</td>
  </tr>
  <tr>
    <td>LChinese</td>
    <td>简体中文</td>
    <td>zh-CHS</td>
  </tr>
  <tr>
    <td>Chinese</td>
    <td>繁体中文</td>
    <td>zh-CHT</td>
  </tr>
  <tr>
    <td>Afrikaans</td>
    <td>南非荷兰语</td>
    <td>af</tdL>
  </tr>
  <tr>
    <td>Amharic</td>
    <td>阿姆哈拉语</td>
    <td>am</td>
  </tr>
  <tr>
    <td>Azeerbaijani</td>
    <td>阿塞拜疆语</td>
    <td>az</td>
  </tr>
  <tr>
    <td>Belarusian</td>
    <td>白俄罗斯语</td>
    <td>be</td>
  </tr>
  <tr>
    <td>Bulgarian</td>
    <td>保加利亚语</td>
    <td>bg</td>
  </tr>
  <tr>
    <td>Bangla</td>
    <td>孟加拉语</td>
    <td>bn</td>
  </tr>
  <tr>
    <td>Bosnian (Latin)</td>
    <td>波斯尼亚语</td>
    <td>bs</td>
  </tr>
  <tr>
    <td>Catalan</td>
    <td>加泰隆语</td>
    <td>ca</td>
  </tr>
  <tr>
    <td>Cebuano</td>
    <td>宿务语</td>
    <td>ceb</td>
  </tr>
  <tr>
    <td>Corsican</td>
    <td>科西嘉语</td>
    <td>co</td>
  </tr>
  <tr>
    <td>Czech</td>
    <td>捷克语</td>
    <td>cs</td>
  </tr>
  <tr>
    <td>Welsh</td>
    <td>威尔士语</td>
    <td>cy</td>
  </tr>
  <tr>
    <td>Danish</td>
    <td>丹麦语</td>
    <td>da</td>
  </tr>
  <tr>
    <td>Greek</td>
    <td>希腊语</td>
    <td>el</td>
  </tr>
  <tr>
    <td>Esperanto</td>
    <td>世界语</td>
    <td>eo</td>
  </tr>
  <tr>
    <td>Estonian</td>
    <td>爱沙尼亚语</td>
    <td>et</td>
  </tr>
  <tr>
    <td>Basque</td>
    <td>巴斯克语</td>
    <td>eu</td>
  </tr>
  <tr>
    <td>Persian</td>
    <td>波斯语</td>
    <td>fa</td>
  </tr>
  <tr>
    <td>Finnish</td>
    <td>芬兰语</td>
    <td>fi</td>
  </tr>
  <tr>
    <td>Fijian</td>
    <td>斐济语</td>
    <td>fj</td>
  </tr>
  <tr>
    <td>Frisian</td>
    <td>弗里西语</td>
    <td>fy</td>
  </tr>
  <tr>
    <td>Irish</td>
    <td>爱尔兰语</td>
    <td>ga</td>
  </tr>
  <tr>
    <td>Scots</td>
    <td>苏格兰盖尔语</td>
    <td>gd</td>
  </tr>
  <tr>
    <td>Galician</td>
    <td>加利西亚语</td>
    <td>gl</td>
  </tr>
  <tr>
    <td>Gujarati</td>
    <td>古吉拉特语</td>
    <td>gu</td>
  </tr>
  <tr>
    <td>Hausa</td>
    <td>豪萨语</td>
    <td>ha</td>
  </tr>
  <tr>
    <td>Hawaiian</td>
    <td>夏威夷语</td>
    <td>haw</td>
  </tr>
  <tr>
    <td>Hebrew</td>
    <td>希伯来语</td>
    <td>he</td>
  </tr>
  <tr>
    <td>Hindi</td>
    <td>印地语</td>
    <td>hi</td>
  </tr>
  <tr>
    <td>Croatian</td>
    <td>克罗地亚语</td>
    <td>hr</td>
  </tr>
  <tr>
    <td>Haitian</td>
    <td>海地克里奥尔语</td>
    <td>ht</td>
  </tr>
  <tr>
    <td>Hungarian</td>
    <td>匈牙利语</td>
    <td>hu</td>
  </tr>
  <tr>
    <td>Armenian</td>
    <td>亚美尼亚语</td>
    <td>hy</td>
  </tr>
  <tr>
    <td>Igbo</td>
    <td>伊博语</td>
    <td>ig</td>
  </tr>
  <tr>
    <td>Icelandic</td>
    <td>冰岛语</td>
    <td>is</td>
  </tr>
  <tr>
    <td>Javanese</td>
    <td>爪哇语</td>
    <td>jw</td>
  </tr>
  <tr>
    <td>Georgian</td>
    <td>格鲁吉亚语</td>
    <td>ka</td>
  </tr>
  <tr>
    <td>Kazakh</td>
    <td>哈萨克语</td>
    <td>kk</td>
  </tr>
  <tr>
    <td>Khmer</td>
    <td>高棉语</td>
    <td>km</td>
  </tr>
  <tr>
    <td>Kannada</td>
    <td>卡纳达语</td>
    <td>kn</td>
  </tr>
  <tr>
    <td>Kurdish</td>
    <td>库尔德语</td>
    <td>ku</td>
  </tr>
  <tr>
    <td>Kyrgyz</td>
    <td>柯尔克孜语</td>
    <td>ky</td>
  </tr>
  <tr>
    <td>Latin</td>
    <td>拉丁语</td>
    <td>la</td>
  </tr>
  <tr>
    <td>Luxembourgish</td>
    <td>卢森堡语</td>
    <td>lb</td>
  </tr>
  <tr>
    <td>Lao</td>
    <td>老挝语</td>
    <td>lo</td>
  </tr>
  <tr>
    <td>Lithuanian</td>
    <td>立陶宛语</td>
    <td>lt</td>
  </tr>
  <tr>
    <td>Latvian</td>
    <td>拉脱维亚语</td>
    <td>lv</td>
  </tr>
  <tr>
    <td>Malagasy</td>
    <td>马尔加什语</td>
    <td>mg</td>
  </tr>
  <tr>
    <td>Maori</td>
    <td>毛利语</td>
    <td>mi</td>
  </tr>
  <tr>
    <td>Macedonian</td>
    <td>马其顿语</td>
    <td>mk</td>
  </tr>
  <tr>
    <td>Malayalam</td>
    <td>马拉雅拉姆语</td>
    <td>ml</td>
  </tr>
  <tr>
    <td>Mongolian</td>
    <td>蒙古语</td>
    <td>mn</td>
  </tr>
  <tr>
    <td>Marathi</td>
    <td>马拉地语</td>
    <td>mr</td>
  </tr>
  <tr>
    <td>Malay</td>
    <td>马来语</td>
    <td>ms</td>
  </tr>
  <tr>
    <td>Maltese</td>
    <td>马耳他语</td>
    <td>mt</td>
  </tr>
  <tr>
    <td>Hmong</td>
    <td>白苗语</td>
    <td>mww</td>
  </tr>
  <tr>
    <td>Myanmar (Burmese)</td>
    <td>缅甸语</td>
    <td>my</td>
  </tr>
  <tr>
    <td>Nepali</td>
    <td>尼泊尔语</td>
    <td>ne</td>
  </tr>
  <tr>
    <td>Dutch</td>
    <td>荷兰语</td>
    <td>nl</td>
  </tr>
  <tr>
    <td>Norwegian</td>
    <td>挪威语</td>
    <td>no</td>
  </tr>
  <tr>
    <td>Nyanja (Chichewa)</td>
    <td>齐切瓦语</td>
    <td>ny</td>
  </tr>
  <tr>
    <td>Querétaro Otomi</td>
    <td>克雷塔罗奥托米语</td>
    <td>otq</td>
  </tr>
  <tr>
    <td>Punjabi</td>
    <td>旁遮普语</td>
    <td>pa</td>
  </tr>
  <tr>
    <td>Polish</td>
    <td>波兰语</td>
    <td>pl</td>
  </tr>
  <tr>
    <td>Pashto</td>
    <td>普什图语</td>
    <td>ps</td>
  </tr>
  <tr>
    <td>Romanian</td>
    <td>罗马尼亚语</td>
    <td>ro</td>
  </tr>
  <tr>
    <td>Sindhi</td>
    <td>信德语</td>
    <td>sd</td>
  </tr>
  <tr>
    <td>Sinhala (Sinhalese)</td>
    <td>僧伽罗语</td>
    <td>si</td>
  </tr>
  <tr>
    <td>Slovak</td>
    <td>斯洛伐克语</td>
    <td>sk</td>
  </tr>
  <tr>
    <td>Slovenian</td>
    <td>斯洛文尼亚语</td>
    <td>sl</td>
  </tr>
  <tr>
    <td>Samoan</td>
    <td>萨摩亚语</td>
    <td>sm</td>
  </tr>
  <tr>
    <td>Shona</td>
    <td>修纳语</td>
    <td>sn</td>
  </tr>
  <tr>
    <td>Somali</td>
    <td>索马里语</td>
    <td>so</td>
  </tr>
  <tr>
    <td>Albanian</td>
    <td>阿尔巴尼亚语</td>
    <td>sq</td>
  </tr>
  <tr>
    <td>Serbian (Cyrillic)</td>
    <td>塞尔维亚语(西里尔文)</td>
    <td>sr-Cyrl</td>
  </tr>
  <tr>
    <td>Serbian (Latin)</td>
    <td>塞尔维亚语(拉丁文)</td>
    <td>sr-Latn</td>
  </tr>
  <tr>
    <td>Sesotho</td>
    <td>塞索托语</td>
    <td>st</td>
  </tr>
  <tr>
    <td>Sundanese</td>
    <td>巽他语</td>
    <td>su</td>
  </tr>
  <tr>
    <td>Swedish</td>
    <td>瑞典语</td>
    <td>sv</td>
  </tr>
  <tr>
    <td>Kiswahili</td>
    <td>斯瓦希里语</td>
    <td>sw</td>
  </tr>
  <tr>
    <td>Tamil</td>
    <td>泰米尔语</td>
    <td>ta</td>
  </tr>
  <tr>
    <td>Telugu</td>
    <td>泰卢固语</td>
    <td>te</td>
  </tr>
  <tr>
    <td>Tajik</td>
    <td>塔吉克语</td>
    <td>tg</td>
  </tr>
  <tr>
    <td>Filipino</td>
    <td>菲律宾语</td>
    <td>tl</td>
  </tr>
  <tr>
    <td>Klingon</td>
    <td>克林贡语</td>
    <td>tlh</td>
  </tr>
  <tr>
    <td>Tongan</td>
    <td>汤加语</td>
    <td>to</td>
  </tr>
  <tr>
    <td>Turkish</td>
    <td>土耳其语</td>
    <td>tr</td>
  </tr>
  <tr>
    <td>Tahitian</td>
    <td>塔希提语</td>
    <td>ty</td>
  </tr>
  <tr>
    <td>Ukrainian</td>
    <td>乌克兰语</td>
    <td>uk</td>
  </tr>
  <tr>
    <td>Urdu</td>
    <td>乌尔都语</td>
    <td>ur</td>
  </tr>
  <tr>
    <td>Uzbek</td>
    <td>乌兹别克语</td>
    <td>uz</td>
  </tr>
  <tr>
    <td>Xhosa</td>
    <td>南非科萨语</td>
    <td>xh</td>
  </tr>
  <tr>
    <td>Yiddish</td>
    <td>意第绪语</td>
    <td>yi</td>
  </tr>
  <tr>
    <td>Yoruba</td>
    <td>约鲁巴语</td>
    <td>yo</td>
  </tr>
  <tr>
    <td>Yucatec</td>
    <td>尤卡坦玛雅语</td>
    <td>yua</td>
  </tr>
  <tr>
    <td>Cantonese (Traditional)</td>
    <td>粤语</td>
    <td>yue</td>
  </tr>
  <tr>
    <td>Zulu</td>
    <td>南非祖鲁语</td>
    <td>zu</td>
  </tr>`;

// 使用正则表达式匹配所有<tr>内的<td>元素内容
const regex = /<tr>\s*<td>(.*?)<\/td>\s*<td>(.*?)<\/td>\s*<td>(.*?)<\/td>\s*<\/tr>/g;

let match;
const supportLangs = [];

while ((match = regex.exec(htmlString)) !== null) {
	// 将匹配的结果添加到数组中
	supportLangs.push({
		lang: match[3], // 'yue' 或 'zu'
		en: match[1],   // 'Cantonese (Traditional)' 或 'Zulu'
		cn: match[2]    // '粤语' 或 '南非祖鲁语'
	});
}

const supportLangObj = supportLangs.reduce((acc, { lang, en, cn }) => {
	acc[lang] = { en, cn };
	return acc;
}, {});

console.log(JSON.stringify(supportLangObj));
